name: Release Please

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release-please-action
        name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
